import type { Metadata } from "next";
import "./globals.css";
import Header from "@/shared/header";
import Footer from "@/shared/footer";

export const metadata: Metadata = {
  title: "Furniture Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
